networks:
  appnet:
    external: true

services:
  php-rms:
    build: .
    container_name: php-ci4-rms
    volumes:
      - .:/var/www/rms
    working_dir: /var/www/rms
    mem_limit: 384m
    restart: always
    networks:
      - appnet